sudo: required
services:
  - docker

before_install:
  - docker build -t jerasmus/docker-react:latest -f Dockerfile.dev .

script:
  - docker run jeramsus/docker-react:latest npm run test -- --coverage
